wealthfront/magellan

magellan-library/src/main/java/com/wealthfront/magellan/Navigator.java
magellan-library/src/main/java/com/wealthfront/magellan/Screen.java
magellan-library/src/test/java/com/wealthfront/magellan/ScreenTest.java

Add a way for a screen to listen for transitions to finish. This allows one to delay view updating and avoid animation jank.

Add optional listeners for transitions

---

magellan-library/src/main/java/com/wealthfront/magellan/Navigator.java
magellan-library/src/main/java/com/wealthfront/magellan/Screen.java

Make it so all actions passed to `whenTransitionFinished { }` from `createView()` on are delayed until the transition is finished (including `onShow`). Also, clarify documentation.
Previously, we immediately ran any code passed to `whenTransitionFinished { }` before the view was measured, which is unintuitive and could have unintended consequences.

Subtly change the definition of whenTransitionFinished

---

magellan-lint/src/main/java/com/wealthfront/magellan/EnforceLifecycleAwareAttachment.kt
magellan-lint/src/main/java/com/wealthfront/magellan/InvalidChildInScreenContainer.kt
magellan-lint/src/main/java/com/wealthfront/magellan/LintRegistry.kt
magellan-lint/src/test/java/com/wealthfront/magellan/EnforceLifecycleAwareAttachmentTest.kt

Example: 
```
Error: In order to make this lifecycle aware work as expected, please attach it to the lifecycle owner with a lifecycle delegate.
Eg. val someObject by lifecycle(SomeObject()) or lateinit var someObject: SomeObject by lateinitLifecycle() [EnforceLifecycleAwareAttachment]
private val rxUnsubscriber = RxUnsubscriber()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Add lint rule to ensure lifecycle aware are attached to lifecycle owners

---

gradle.properties
magellan-legacy/src/main/java/com/wealthfront/magellan/HistoryRewriter.java
magellan-legacy/src/main/java/com/wealthfront/magellan/HistoryRewriterExtensions.kt
magellan-legacy/src/main/java/com/wealthfront/magellan/LegacyExpedition.kt
magellan-legacy/src/main/java/com/wealthfront/magellan/NavigationType.kt
magellan-legacy/src/main/java/com/wealthfront/magellan/Navigator.kt
magellan-legacy/src/main/java/com/wealthfront/magellan/Screen.java
magellan-legacy/src/test/java/com/wealthfront/magellan/HistoryRewriterExtensionsKtTest.kt
magellan-library/src/main/java/com/wealthfront/magellan/ScreenContainer.java
magellan-library/src/main/java/com/wealthfront/magellan/navigation/LinearNavigator.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationEvent.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationTraverser.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/Navigator.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/LinearNavigatorTest.kt

This PR adds better backwards compatibility support for the HistoryRewriter APIs. This should make the migration simpler and support the old use cases better.

Add compatibility for history rewriting APIs and rename LegacyNavigator

---

magellan-library/src/main/java/com/wealthfront/magellan/Direction.kt
magellan-library/src/main/java/com/wealthfront/magellan/debug/StatePrinter.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleAwareComponent.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleRegistry.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt
magellan-library/src/test/java/com/wealthfront/magellan/debug/StatePrinterTest.kt
magellan-library/src/test/java/com/wealthfront/magellan/lifecycle/LifecycleLimiterTest.kt

Whoops, this is getting pretty big. Here's what's here:
- Refactor NavigationDelegate to be based on LifecycleLimiter
- Fix some issues with LifecycleLimiter
- Properly transition states
- Only pass backPressed() events to Shown or Resumed children
- Add assertions for transitioning lifecycles from unexpected states and attaching or detaching multiple times
- Fix a bug in the StatePrinter

Fix navigation delegate

---

magellan-legacy/src/main/java/com/wealthfront/magellan/LegacyViewComponent.java
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/ActivityLifecycleAdapter.kt

Some lifecycle components will hold on to the `Created` lifecycle state object, which can therefore live longer than an activity. We shouldn't pass an activity context for `Created` to prevent these leaks.

Pass application context in create() and destroy() to prevent leaks

---

magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleExtensions.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt

- Properly detach items from the navigator in onDestroy
- Make `by lateinitLifecycle` idempotent (i.e. allow setting the property multiple times)

Better handle onDestroy events

---

magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleRegistry.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleStateMachine.kt
magellan-library/src/test/java/com/wealthfront/magellan/lifecycle/LifecycleStateMachineTest.kt

We hang on to the `Created` event object potentially long past the associated activity is destroyed.
I don't like how opaque the API is now, however. We should consider passing in `Application` and `Activity` objects to make the different lifecycle events have explicitly different types of `Context`. But later.

Avoid leaking activity context by passing application context to Created

---

magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/ActivityLifecycleAdapter.kt

This highlights the main difference between Magellan's and android's default lifecycle management; in Magellan world, children are set up before their parents so the parent can interact with them in the corresponding lifecycle event. Calling onCreate immediately here allows us to keep Magellan's mental model when interacting with our `Expedition` it in an activity.

Call onCreate immediately when attaching to activity lifecycle

---

magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/ActivityLifecycleAdapter.kt

Should fix the bug we're seeing around one activity being started before the other one's torn down.
Unfortunately, gradle isn't working on my m1 mac so I can't run it right now. I added tests in another PR so we can merge this and get those working when I have my laptop again.

Fix overlapping activities bug

---

magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt

this should fix memory leaks we see when the Activity gets torn down by the system

Null-out view reference in onStop

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/Versions.kt
magellan-sample/src/androidTest/java/com/wealthfront/magellan/uitest/DialogTest.kt

So that test activities have Android 12-friendly export settings. Namely avoids errors like:
```
/Users/chrismathew/dev/Ferdinand/app/src/main/AndroidManifest.xml Error:
android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
```

Bump test libs to support Android 12

---

magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/LinearNavigatorTest.kt

Having the same navigable in multiple places in the backstack caused an issue in our main app earlier. Even before this PR, we enforce that you can attach a `LifecycleAware` to a given `LifecycleOwner` at most once, but the way we detect changes in the backstack (so we can properly attach/detach navigables) means that we didn't properly enforce that for `NavigationDelegate`. Now, we will crash if you try to add a single instance to the backstack multiple times.
(This has been sitting on my laptop for a while, whoops. 😅)

Prevent multiple instances of the same Navigable on the backstack

---

gradle/gradle-mvn-push.gradle

With an issue to add them back in #207. I think it's a Java 11 change that's causing this to happen, but javadoc compilation doesn't work in our project anymore, even for released versions of the library.
We also don't have a lot of java code in the library anymore, so this should be fine.

Remove javadoc-generating gradle targets

---

README.md

It only had the 3 classes that were in java, so it wasn't even useful

Remove javadoc link from readme

---

magellan-legacy/src/main/java/com/wealthfront/magellan/LegacyExpedition.kt
magellan-legacy/src/main/java/com/wealthfront/magellan/Navigator.kt
magellan-library/src/main/java/com/wealthfront/magellan/core/Journey.kt
magellan-library/src/main/java/com/wealthfront/magellan/init/Magellan.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/DefaultLinearNavigator.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationOverrideProvider.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/Navigator.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/DefaultLinearNavigatorTest.kt
magellan-sample-advanced/build.gradle
magellan-sample-advanced/src/androidTest/java/com/wealthfront/magellan/uitest/NavigationTest.kt
magellan-sample-advanced/src/main/java/com/wealthfront/magellan/sample/advanced/RootJourney.kt
magellan-sample-advanced/src/main/java/com/wealthfront/magellan/sample/advanced/SampleApplication.kt
magellan-sample-advanced/src/main/java/com/wealthfront/magellan/sample/advanced/designcereal/DesignCerealJourney.kt
magellan-sample-advanced/src/main/java/com/wealthfront/magellan/sample/advanced/suggestexhibit/SuggestConfirmationStep.kt
magellan-sample-advanced/src/main/java/com/wealthfront/magellan/sample/advanced/suggestexhibit/SuggestExhibitJourney.kt
magellan-sample-advanced/src/main/res/layout/suggest_exhibit_confirmation.xml
magellan-sample-advanced/src/main/res/values/strings.xml

meanwhile if it's an operation we want, then just continue as normal.
The problem of the [existing "dry run" approach](https://github.com/wealthfront/magellan/pull/230/files#r789325119) is that it potentially runs all backstack operations twice - once for the "dry run", and again "for real". This causes problems if you have non-idempotent state changes inside a backstack operation (example: manipulating the intent on an Activity during deeplinking logic). 
With this approach, we're guaranteed to only run each backstack operation once.

Conditionally restore backstack to undo unwanted operations

---

RELEASING.md

Oops: https://www.markdownguide.org/basic-syntax/#ordered-list-best-practices. 
Pro tip, use the "Rich Diff" viewer for future Markdown edits: https://github.com/wealthfront/magellan/pull/243/files?short_path=87d6a57#diff-87d6a57a759f2386bf9caf5309b9aa0b9ff0ca70f5e38696e114a1ccdb0e785d

Fix release instruction formatting

---

magellan-legacy/src/main/java/com/wealthfront/magellan/LegacyJourney.kt
magellan-legacy/src/main/java/com/wealthfront/magellan/Screen.java
magellan-legacy/src/main/java/com/wealthfront/magellan/ScreenGroup.java
magellan-library/src/main/java/com/wealthfront/magellan/core/Journey.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigableCompat.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationTraverser.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/NavigationTraverserTest.kt

Allow application developers to customize navigation traverser behavior by overriding createSnapshot. This is useful for more advanced navigation use-cases like master-detail or tabbed navigables.

Customizing NavigationTraverser

---

gradle.properties

this option works on both Java 11 and Java 17 per my testing

Migrate JVM option names to support Java 17

---

magellan-library/src/main/java/com/wealthfront/magellan/navigation/LinearNavigatorExtensions.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/LinearNavigatorExtensionsTest.kt

API provides:
`goBackTo(navigable)`
`goBackBefore(navigable)`
`goBackToRoot()`
`goForwardToRoot()`
`resetWithRoot(navigable)`
`clearUntilRootAndGoTo(navigable)`

Adds several navigation helper shorthand functions to LinearNavigator.

---

magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/DefaultLinearNavigatorTest.kt

Fixes back press being propagated twice to active children of NavigationDelegate.
`NavigationDelegate` is a `LifecycleAwareComponent`. All `LifecycleAwareComponent`s forward back presses to active children (active means lifecycle state >= Shown). `NavigationDelegate` was then calling back press on its `currentNavigable`, which is also a lifecycle aware child. The result is that `currentNavigable` would receive back press twice: once from `LifecycleAwareComponent` code and once from `NavigationDelegate` code.

Fix double back press

---

magellan-library/src/main/java/com/wealthfront/magellan/transitions/CircularRevealTransition.kt

if view cannot be found (e.g. due to backstack modification) than play a fullscreen circular transition
to repro the issue yourself, you can check out `circular-fallback-demo` and:
1.) Click "Start next journey" (top of screen)
2.) Click "Start next journey" (last choice in list)
3.) Press back

Provide fallback for CircularRevealTransition

---

magellan-sample-migration/build.gradle
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/AppComponent.java
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/AppModule.java
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/Expedition.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/tide/DogBreedsStep.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/tide/DogDetailsScreen.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/tide/DogDetailsView.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/tide/DogListStep.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/toolbar/ToolbarHelper.kt
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/TestAppComponent.java
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/TestAppModule.java
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/TestExtensions.kt
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/tide/DogBreedsStepTest.kt
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/tide/DogDetailsScreenTest.kt
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/tide/DogListStepTest.kt
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/tide/HelpViewTest.kt
magellan-sample-migration/src/test/resources/robolectric.properties

- mock toolbar helper in tests
- use setContentScreen where possible
- configure Robolectric via properties file where possible

Basic unit tests for all sample-migration screens

---

build.gradle
buildSrc/build.gradle
buildSrc/src/main/java/Plugins.kt
buildSrc/src/main/java/Versions.kt
gradle/libs.versions.toml

to avoid confusing limitations and issues
rolls back some changes https://github.com/wealthfront/magellan/pull/297/files. Also, adds kotlin-gradle-plugin to buildSrc to ensure we're using the desired Kotlin version. This is especially important for the Compose toolchain

Don't use version catalog for project level plugin mgmt

---

magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationTraverser.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/NavigationTraverserTest.kt

`NavigationTraverser` was exponentially increasing it's indentation the deeper the backstack. Once the backstack is deep enough, the logs become quite difficult to read. Here's an example showing the indentation issue as outputted by the test `globalBackStackWithSiblingJourney`. This PR fixes the issue highlighted by the test.

Fix NavigationTraverser indentation

---

.github/workflows/runTests.yml

see https://github.com/gradle/gradle-build-action/releases/tag/v3.4.2

Replace Gradle build action with successor

---

magellan-library/src/main/java/com/wealthfront/magellan/navigation/LazySetNavigator.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/LazySetNavigatorTest.kt

Adding support for `LazySetNavigator` to remove navigables
- Can remove a single Navigable
- Can remove multiple Navigables
- Can update the navigator's Navigables which can add and remove Navigables

Support removing navigables from LazySetNavigator
