gradle.properties
magellan-library/gradle.properties

Switch to Maven Central

---

.idea/modules.xml
magellan-sample/src/main/java/com/wealthfront/magellan/sample/DetailScreen.java
magellan-sample/src/main/java/com/wealthfront/magellan/sample/DetailView.java
magellan-sample/src/main/java/com/wealthfront/magellan/sample/HomeScreen.java
magellan-sample/src/main/java/com/wealthfront/magellan/sample/HomeView.java
magellan-sample/src/main/java/com/wealthfront/magellan/sample/MainActivity.java
magellan-sample/src/main/res/layout/detail.xml
magellan-sample/src/main/res/layout/home.xml
magellan-sample/src/main/res/layout/main_activity.xml
magellan-sample/src/main/res/values-w820dp/dimens.xml
magellan-sample/src/main/res/values/dimens.xml
magellan-sample/src/main/res/values/strings.xml

Adds use of navigator with home screen and detail screen to demonstrate basic navigation capabilities

Add basic navigation examples to basic sample app

---

.travis.yml
magellan-library/build.gradle
magellan-sample/src/main/java/com/wealthfront/magellan/sample/DetailScreen.java
magellan-sample/src/main/java/com/wealthfront/magellan/sample/DetailView.java
magellan-sample/src/main/java/com/wealthfront/magellan/sample/HomeScreen.java
magellan-sample/src/main/java/com/wealthfront/magellan/sample/HomeView.java

Add travis

---

magellan-library/src/main/java/com/wealthfront/magellan/Screen.java

Make it so setTitle accepts a string on top of the existing @StringRes

Screen setTitle takes a CharSequence

---

magellan-library/src/main/java/com/wealthfront/magellan/Navigator.java

A method to accept navigation type for goBackTo just like goBackBefore
Also replace magallen with navigation in some places

Gobackto with navigation type

---

.idea/misc.xml
.travis.yml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
magellan-library/build.gradle
magellan-rx/build.gradle
magellan-rx2/build.gradle
magellan-sample-advanced/build.gradle
magellan-sample/build.gradle
magellan-support/build.gradle
magellan-support/src/main/java/com/wealthfront/magellan/support/SingleActivity.java
magellan-support/src/main/res/values/strings.xml

The dependencies are getting a little stale and I got tired of android studio complaining, so I updated them all to the latest versions as of today.
I left out espresso because it had some breaking changes in 3.0 and I don't know enough about it to know the potential repercussions.

Update dependencies except espresso (2017-02-25)

---

magellan-library/src/main/java/com/wealthfront/magellan/Navigator.java
magellan-library/src/test/java/com/wealthfront/magellan/DummyScreen.java
magellan-library/src/test/java/com/wealthfront/magellan/NavigatorTest.java
magellan-library/src/test/java/com/wealthfront/magellan/ScreenGroupTest.java
magellan-library/src/test/java/com/wealthfront/magellan/ScreenTest.java

Add screen name to preconditions when an exception is thrown for when the screen is not present in backstack

Add screen name to preconditions

---

gradle/gradle-mvn-push.gradle
magellan-library/src/main/java/com/wealthfront/magellan/core/Navigable.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleAware.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleAwareComponent.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleExtensions.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleOwner.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleRegistry.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleState.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleStateMachine.kt
magellan-library/src/main/java/com/wealthfront/magellan/view/LifecycleViewBinding.kt
magellan-library/src/test/java/com/wealthfront/magellan/lifecycle/LifecycleStateMachineTest.kt
magellan-library/src/test/java/com/wealthfront/magellan/lifecycle/LifecycleStateTest.kt
magellan-library/src/test/java/com/wealthfront/magellan/view/LifecycleViewTest.kt

- Added LifecycleAware
- Added LifecycleOwner
- Added LifecycleRegistry
- Added LifecycleState.kt
- Added LifecycleStateMachine

Add core lifecycle components

---

magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/Expedition.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/LinearNavigator.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigableListener.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationPropagator.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationTraverser.kt

This allows us to listen to onShow/onHide events of our navigables. And in general, just an onNavigate event to reset the menu, etc..

Add NavigationPropagator to propagate navigation events

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/Versions.kt
magellan-journey-sample/build.gradle
magellan-journey-sample/src/main/AndroidManifest.xml
magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/App.kt
magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/AppComponent.kt
magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/AppModule.kt
magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/DetailStep.kt
magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/Expedition.kt
magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/ExpeditionProvider.kt
magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/FirstJourney.kt
magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/MainActivity.kt
magellan-journey-sample/src/main/java/com/wealthfront/magellan/sample/Toaster.kt
magellan-library/build.gradle
magellan-library/src/main/java/com/wealthfront/magellan/core/NavigableExtensions.kt
magellan-library/src/main/java/com/wealthfront/magellan/lifecycle/LifecycleRegistry.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/LoggingNavigableListener.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationPropagator.kt
magellan-library/src/test/java/com/wealthfront/magellan/core/NavigableExtensionsKtTest.kt
magellan-library/src/test/java/com/wealthfront/magellan/lifecycle/LifecycleRegistryTest.kt

Since I paused the menu component PR, I decoupled the dependency injection i had as a bonus in that PR.

Add Dependency injection for magellan sample

---

RELEASING.md
build.gradle
gradle/gradle-mvn-push.gradle

Same thing as I did with [Blend](https://github.com/wealthfront/blend/pull/19), should help with testing changes locally in other projects.
Most of the changes are from [Chris Banes' project](https://github.com/chrisbanes/gradle-mvn-push), some are from scouring the internet for the few missing pieces.

Update gradle-mvn-push script to support publishing to mavenLocal

---

magellan-legacy/src/main/java/com/wealthfront/magellan/HistoryRewriterExtensions.kt
magellan-legacy/src/main/java/com/wealthfront/magellan/Navigator.kt

This allows us to support override transition's behavior in a backwards compatible way.

Add compatibility APIs for override transition

---

CHANGELOG.md
README.md
gradle.properties

Prepare for release 2.0.0-beta

---

gradle/gradle-mvn-push.gradle
magellan-legacy/src/main/java/com/wealthfront/magellan/ScreenLifecycleListener.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/CurrentNavigableProvider.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/LoggingNavigableListener.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigableListener.java
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationPropagator.kt
magellan-sample-advanced/src/main/java/com/wealthfront/magellan/sample/advanced/toolbar/ToolbarHelper.kt

- Sneaky: update library dependency to snapshot

Rename methods for clarity and fix issue in showing hidden screens

---

gradle.properties
magellan-library/src/main/java/com/wealthfront/magellan/debug/StatePrinter.kt
magellan-library/src/test/java/com/wealthfront/magellan/debug/StatePrinterTest.kt

This should help us debug things.

Add state printer

---

magellan-library/src/main/java/com/wealthfront/magellan/debug/StatePrinter.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationTraverser.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/NavigationTraverserTest.kt

Nicer BackStack description

---

CHANGELOG.md
README.md

Prepare for release 2.1.0 

---

internal-test-support/src/main/java/com/wealthfront/magellan/internal/test/DummyStep.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt
magellan-library/src/test/java/com/wealthfront/magellan/navigation/DefaultLinearNavigatorTest.kt

Fixes #79. Not urgent but just saw this opportunity cleaning out old issues and PRs

Call transitionStarted and transitionFinished in onShow, too

---

magellan-legacy/src/main/java/com/wealthfront/magellan/Navigator.kt
magellan-library/src/main/java/com/wealthfront/magellan/navigation/NavigationDelegate.kt

Our `Navigator` implementations appeared to be extensible, but weren't actually. This came up when working through our toolbar patterns, which I'll write a wiki page about soon.

Open Navigator to extension

---

magellan-legacy/src/main/java/com/wealthfront/magellan/LegacyStep.kt

Add ShownLifecycleScope to LegacyStep

---

CHANGELOG.md
README.md
gradle.properties

PR for last time we did this: https://github.com/wealthfront/magellan/pull/224

Prepare for release 2.1.6-beta

---

gradle.properties

this will give the artifact a unique ID should you [publish it to a local Maven](https://github.com/wealthfront/magellan/blob/master/RELEASING.md)

Prepare for next development cycle (2.1.7-SNAPSHOT)

---

CHANGELOG.md
README.md
gradle.properties

last time we did this: https://github.com/wealthfront/magellan/pull/232

Prepare for release 2.1.7-beta

---

CHANGELOG.md
README.md
gradle.properties

Last time we did this: https://github.com/wealthfront/magellan/pull/233

Prepare for next development cycle (2.1.8-SNAPSHOT)

---

CHANGELOG.md
gradle.properties

Last time we did this: https://github.com/wealthfront/magellan/pull/236/files

Prepare for release 2.1.8-beta

---

CHANGELOG.md
README.md
gradle.properties

last time we did this: https://github.com/wealthfront/magellan/pull/244

Prepare for release 2.1.10-beta

---

gradle.properties

Last time we did this: https://github.com/wealthfront/magellan/pull/246

Prepare next development version 2.1.11-SNAPSHOT

---

magellan-legacy/src/main/java/com/wealthfront/magellan/LegacyStep.kt

Expose LegacyStep's DialogComponent instance

---

.github/workflows/runTests.yml
buildSrc/build.gradle
buildSrc/src/main/kotlin/Versions.kt
gradle/wrapper/gradle-wrapper.properties
internal-test-support/build.gradle
magellan-legacy/build.gradle
magellan-library/build.gradle
magellan-library/src/test/java/com/wealthfront/magellan/coroutines/CreatedLifecycleScopeTest.kt
magellan-library/src/test/java/com/wealthfront/magellan/coroutines/ShownLifecycleScopeTest.kt
magellan-lint/src/test/java/com/wealthfront/magellan/AvoidUsingActivityTest.kt
magellan-lint/src/test/java/com/wealthfront/magellan/EnforceLifecycleAwareAttachmentTest.kt
magellan-lint/src/test/java/com/wealthfront/magellan/InvalidChildInScreenContainerTest.kt
magellan-rx/build.gradle
magellan-rx2/build.gradle
magellan-test/build.gradle

Kotlin to 1.6.20
AGP to 7.2.2
- minor style changes
- update optIn annotations and flags

Update Kotlin + Gradle plugins

---

CHANGELOG.md
README.md
gradle.properties

last time we did this: https://github.com/wealthfront/magellan/pull/249

Prepare for release 2.2.0-beta

---

CHANGELOG.md
README.md
gradle.properties

last time we did this: https://github.com/wealthfront/magellan/pull/258

Prepare for release 2.2.1-beta

---

gradle.properties

Last time we did this: https://github.com/wealthfront/magellan/pull/250

Prepare next development version 2.2.2-SNAPSHOT

---

magellan-legacy/src/main/java/com/wealthfront/magellan/Screen.java
magellan-library/src/main/java/com/wealthfront/magellan/view/DialogComponent.kt
magellan-sample/src/androidTest/java/com/wealthfront/magellan/DisableAnimationsAndKeyboardRule.kt
magellan-sample/src/androidTest/java/com/wealthfront/magellan/uitest/DialogTest.kt
magellan-sample/src/main/java/com/wealthfront/magellan/sample/DetailStep.kt
magellan-sample/src/main/java/com/wealthfront/magellan/sample/DialogStep.kt
magellan-sample/src/main/java/com/wealthfront/magellan/sample/SecondJourney.kt
magellan-sample/src/main/res/layout/detail.xml
magellan-sample/src/main/res/layout/empty.xml
magellan-sample/src/main/res/values/strings.xml

Ensure DialogComponent is capable of rendering a dialog requested immediately in onShow of a Step

Fixes DialogComponent

---

CHANGELOG.md
README.md
gradle.properties

last time we did this: https://github.com/wealthfront/magellan/pull/276

Prepare for release 2.2.6-beta

---

gradle.properties

last time we did this: https://github.com/wealthfront/magellan/pull/271

Prepare next development version 2.2.7-SNAPSHOT

---

.github/workflows/runTests.yml

should fix errors like https://github.com/wealthfront/magellan/actions/runs/6277507633/job/17049408457

Fix: Setup JDK v17 before building

---

buildSrc/src/main/java/Libs.kt
magellan-sample-migration/build.gradle
magellan-sample-migration/src/androidTest/java/com/wealthfront/magellan/IntegrationTestRunner.kt
magellan-sample-migration/src/androidTest/java/com/wealthfront/magellan/uitest/NavigationTest.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/AppModule.java
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/api/DogApi.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/tide/DogDetailsScreen.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/tide/HelpScreen.kt
magellan-sample-migration/src/main/res/layout/dog_details.xml
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/tide/HelpScreenTest.kt

also, migrate this app to RxJava 2

Add basic integration test to sample app

---

buildSrc/src/main/java/Versions.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/Expedition.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/tide/DogDetailsScreen.kt
magellan-sample-migration/src/main/java/com/wealthfront/magellan/sample/migration/tide/DogListStep.kt
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/TestAppComponent.kt
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/tide/DogDetailsScreenTest.kt
magellan-sample-migration/src/test/java/com/wealthfront/magellan/sample/migration/tide/DogListStepTest.kt

this will make providing mocks more straightforward in tests

Use constructor injection in sample app

---

buildSrc/src/main/java/Versions.kt
gradle/libs.versions.toml
magellan-sample-migration/build.gradle

...and update compile SDK version as needed

Add compose libs to sample project

---

CHANGELOG.md
README.md
gradle.properties

last time we did this https://github.com/wealthfront/magellan/pull/296

Prepare for release 2.2.8-beta
